### ISSUE TITLE
Doesn't raise expeception when connection is refused by Fantozzi server

### ISSUE THREAD

**Issue by michaljuris** [ucetnictvi-on-line/pina#9]
When connection to server is refused or will time out; Pina does return:

```
pry(main)> p = Pina::Contact.find_by(company_number: 27608421)
=> #<Pina::RestAdapter::Response:0xaf0454c @body="", @status_code=0>
```

It should raise exception instead. Something like:

```
Errno::ECONNREFUSED: Connection refused - connect(2) for "xxxxxxx" port xxxx
```

**Comment by PHronek** [comment]
You're right, i'll look into that ASAP.

**Comment by hovancik** [comment]
Seems that Tyhpoeus returns status code 0, when he does not know what went wrong.

See:  https://github.com/typhoeus/typhoeus#handling-http-errors

```
  elsif response.code == 0
    # Could not get an http response, something's wrong.
    log(response.return_message)
  else
```

**Comment by michaljuris** [comment]
@hovancik 

according this PR - https://github.com/typhoeus/typhoeus/pull/498/files - it raises an exception when Faraday is used.

@PHronek - so we've another reason to use Faraday ;)

**Comment by hovancik** [comment]
@michaljuris according to my local Gemfile.lock we are using https://github.com/typhoeus/ethon, not Faraday

**Comment by PHronek** [comment]
Simple fix in Pina should be enough for now. #12
